spring:
  profiles:    active: jdbc, native
  cloud:
    config:      server:
        default-label: DGC
        default-profile: local                        jdbc:          enabled: true
          order: 1
          sql: SELECT KEY, VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?          
        native:          
          order: 2
          search-locations:          - file:///./config
          - file:///./config/{application}
  datasource:    url: jdbc:h2:file:./configdb
    password: configdb
    username: configdb
  h2:    console:      enabled: true
      path: /h2-console
server:
  port: 8888
  
management:  endpoint:    health:      enabled: true
      probes:        enabled: false
    metrics:      enabled: true
    configprops:      enabled: true  endpoints:    web:      exposure:        include: '*'logging:  level:    web: DEBUG
    '[org.h2.jdbc]': DEBUG
    '[org.hibernate]': DEBUG    
    root: DEBUG