spring:
  profiles:
    active: jdbc, native, git
  application:
    name: demo-config-server
  cloud:
    config:      
      server:
        default-label: main
        default-profile: dev                
        jdbc:
          enabled: true
          order: 3
          sql: SELECT KEY, VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?          
        native:          
          order: 2
          search-locations:
          - file:///./config
          - file:///./config/{application}
        git:
          order: 1
          label: main
          #uri: "D:/development/GitHub/techfridays/demo-configs"
          uri: https://github.com/aps-dnxt/config-client.git
          ref: main
          search-paths:
            - '{application}'
          

  datasource:
    url: jdbc:h2:file:./configdb
    password: configdb
    username: configdb
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8888
  
management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: false
    metrics:
      enabled: true
    configprops:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    web: DEBUG
    '[org.h2.jdbc]': INFO
    '[org.hibernate]': INFO    
    root: INFO